name: dlsmm

on:
  workflow_dispatch:
    inputs:
      opencv-version:
        description: untia
        required: true
        default: 4.5.2

jobs:
  opencv:
    strategy:
      matrix:
        include:
          - name: windows_amd64
            os: windows-latest

    name: "OpenCV ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    

    steps:
      - name: delpdb
        run: |
            c:
            cd C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC
            dir
        shell: cmd
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sutaz.zip
          path: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\lib\x64
            
