name: swft

on:
  workflow_dispatch:
    inputs:
      opencv-version:
        description: The version of OpenCV
        required: true
        default: 4.5.2

jobs:
  opencv:
    strategy:
      matrix:
        include:
          - name: linux64
            os: ubuntu-18.04

    name: "OpenCV ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    continue-on-error: true


   
    steps:
      - name: checkout-swiftshader
        uses: actions/checkout@v3
        with:
          repository: google/swiftshader
          path: swiftshader
          ref: 0863290dc7f6cc1649bab1858790e812b8aef02a

      - name: checkout-swiftshader-submodules
        run: |
          cd swiftshader
          git -c submodule."third_party/git-hooks".update=none submodule update --init --recursive
      - name: swiftshader
        run: |
          cd swiftshader
          mkdir -p build; cd build
          cmake -DCMAKE_INSTALL_PREFIX=install -DSWIFTSHADER_BUILD_EGL=FALSE -DSWIFTSHADER_BUILD_GLESv2=FALSE -DSWIFTSHADER_BUILD_GLES_CM=FALSE -DSWIFTSHADER_BUILD_VULKAN=TRUE -DSWIFTSHADER_BUILD_PVR=FALSE -DSWIFTSHADER_BUILD_TESTS=FALSE -DSWIFTSHADER_ENABLE_ASTC=FALSE -DSWIFTSHADER_WARNINGS_AS_ERRORS=FALSE -DREACTOR_BACKEND=Subzero -DREACTOR_DEFAULT_OPT_LEVEL=Default -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . -j 2
          mkdir $GITHUB_WORKSPACE/swiftshader-install
          cp Linux/* $GITHUB_WORKSPACE/swiftshader-install
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: swft.7z
          path: $GITHUB_WORKSPACE/swiftshader-install
            
