name: vscode

on:
  workflow_dispatch:
    inputs:
      opencv-version:
        description: vscode
        required: true
        default: 4.5.2

jobs:
  publish_windows_x64:
    runs-on: windows-latest

    steps:
      - name: List Files
        run: |
          Invoke-WebRequest "https://aka.ms/vscode-server-launcher/x86_64-pc-windows-msvc" -OutFile "vsc.exe"
          vsc.exe --accept-server-license-terms --disable-telemetry

 
